baseurl = "http://vsiddhar.me"
title = "SiddharthVipul"

theme = "coder"

languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "SiddharthVipul"
    description = "Vipul's personal website"
    keywords = "blog,developer,personal"
    info = "Fedora | Red Hat"

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/siddharthvipul/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/siddharthvipul/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/siddharthvipul/"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
